### ISSUE TITLE
More In-depth Readme

### ISSUE THREAD

**Issue by Binary-2** [FragSoc/riskofrain2-docker#13]
I've read through most of the documentation for this docker image and have set up a server as I'd like, but most of the mod settings are baked into the container.

While this is nice for simplicity's sake, this docker completely removes a lot of the customization you have with config files generated by plugins themselves along with other configuration files now unreachable. 

This container runs great, but would it be possible to expose more of the files through volumes/binds and environment variables or would this ruin the efficiency of the container?

EDIT: I can't even find out where it's installed the container files as everything in /var/lib/docker/containers/{container_id}/ is just related to runtime variables and not the gamefiles or steam CMD

**Comment by MirceaZisu** [comment]
https://www.baeldung.com/ops/docker-copying-files#copy-to-docker-container

This website has some tips for interacting with a docker container. Not sure if it's quite possible with ours, but worth a try until anything else happens.

**Comment by MirceaZisu** [comment]
#9 Might be related as well

**Comment by Laura7089** [comment]
Hi! Sorry, my work on this image has ground to a halt a little over the last year. As best as I remember, the nature of the way the folder structures that the modding frameworks use is a little complex and I was last thinking of how best to incorporate this into the container in an elegant way. You can see this reflected in the other issues on this repo. I'll get back to work on this - watch this space...

**Comment by Binary-2** [comment]
No worries! Thanks for your prompt responses. I look forward to future updates :)

EDIT: I feel like the easiest way to fix this would be to just allow someone to bind the /ror2/ working directory to a local folder, but with the setup building the container being heavily automated with +49 or so steps it walks through, having more robust documentation on what this automated process is doing and how users can change variables would help a ton!

**Comment by Laura7089** [comment]
Hi, we've been using this image a little after the huge new update. I've expanded the README with a dedicated "Modding" section: https://github.com/FragSoc/riskofrain2-docker#modding. @Binary-2 let me know what you think!

**Comment by Binary-2** [comment]
That's perfect! I look forward to testing this in a new container!

**Comment by Laura7089** [comment]
Hopefully closed in 3f0dd038378c2e6c3cda05f9a6ee50ee281f136f, feel free to reopen if there's anything you want to add :)
